syntax = "proto2";

message ipc_var_entry {
    required uint32 sem_ctls_max = 1;
    required uint32 msg_ctlmax = 2;
    required uint32 msg_max = 3;
    required uint32 msg_mnb = 4;
    required uint32 auto_msgmni = 5;
    required uint32 shmmax = 6;
    required uint32 shmall = 7;
    required uint32 shmmni = 8;
    required uint32 shm_ctls_max = 9;
    required uint32 shm_rmid_forced = 10;
    required uint32 mq_queues_max = 11;
    required uint32 mq_msg_max = 12;
    required uint32 mq_msgsize_max = 13;
    required uint32 mq_msg_default = 14;
    required uint32 mq_msgsize_default = 15;
}
